// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entity/jwt.dart';
import 'entity/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7343022369758524994),
      name: 'Jwt',
      lastPropertyId: const IdUid(13, 4101795790848201024),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2997388197605048374),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 700699502899145371),
            name: 'lastUpdatedAt',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 2067673302026979064),
            name: 'token',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 4101795790848201024),
            name: 'tokenType',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 863897412781948733),
      name: 'User',
      lastPropertyId: const IdUid(14, 3550572966060621169),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1953664417556711904),
            name: 'objectBoxId',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(5, 49551375918934146),
            name: 'userName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 7196955451868114213),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1684180377040897874),
            name: 'tokenId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 1587160166785019890),
            relationTarget: 'Jwt'),
        ModelProperty(
            id: const IdUid(9, 2229594509470191251),
            name: 'lastUpdatedAt',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 1114967368223305790),
            name: 'environment',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 3423741387045359741),
            name: 'isDark',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 698533130156835837),
            name: 'defaultLocale',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 3550572966060621169),
            name: 'phoneNumber',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 863897412781948733),
      lastIndexId: const IdUid(2, 1587160166785019890),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [2957674131869971758],
      retiredPropertyUids: const [
        463684839024402313,
        2891864814578009964,
        5017529633868221986,
        4319967632291168320,
        7557825774822024276,
        2747992633915691583,
        3469727455246878399,
        2936600721406616600,
        7748449109121943328,
        5777761957073788737,
        6308805970911218673,
        4119063846641623970,
        7921785593112178603,
        5037747737811843491
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Jwt: EntityDefinition<Jwt>(
        model: _entities[0],
        toOneRelations: (Jwt object) => [],
        toManyRelations: (Jwt object) => {},
        getId: (Jwt object) => object.objectBoxId,
        setId: (Jwt object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (Jwt object, fb.Builder fbb) {
          final tokenOffset = fbb.writeString(object.token);
          final tokenTypeOffset = fbb.writeString(object.tokenType);
          fbb.startTable(14);
          fbb.addInt64(0, object.objectBoxId);
          fbb.addInt64(2, object.lastUpdatedAt.millisecondsSinceEpoch);
          fbb.addOffset(11, tokenOffset);
          fbb.addOffset(12, tokenTypeOffset);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Jwt()
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..lastUpdatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0))
            ..token = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 26, '')
            ..tokenType = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 28, '');

          return object;
        }),
    User: EntityDefinition<User>(
        model: _entities[1],
        toOneRelations: (User object) => [object.token],
        toManyRelations: (User object) => {},
        getId: (User object) => object.objectBoxId,
        setId: (User object, int id) {
          object.objectBoxId = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final userNameOffset = fbb.writeString(object.userName);
          final emailOffset = fbb.writeString(object.email);
          final environmentOffset = fbb.writeString(object.environment);
          final defaultLocaleOffset = fbb.writeString(object.defaultLocale);
          final phoneNumberOffset = fbb.writeString(object.phoneNumber);
          fbb.startTable(15);
          fbb.addInt64(0, object.objectBoxId);
          fbb.addOffset(4, userNameOffset);
          fbb.addOffset(5, emailOffset);
          fbb.addInt64(6, object.token.targetId);
          fbb.addInt64(8, object.lastUpdatedAt.millisecondsSinceEpoch);
          fbb.addOffset(9, environmentOffset);
          fbb.addBool(11, object.isDark);
          fbb.addOffset(12, defaultLocaleOffset);
          fbb.addOffset(13, phoneNumberOffset);
          fbb.finish(fbb.endTable());
          return object.objectBoxId;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User()
            ..objectBoxId =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..userName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..email = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..lastUpdatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0))
            ..environment = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 22, '')
            ..isDark =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 26, false)
            ..defaultLocale = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 28, '')
            ..phoneNumber = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 30, '');
          object.token.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.token.attach(store);
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Jwt] entity fields to define ObjectBox queries.
class Jwt_ {
  /// see [Jwt.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<Jwt>(_entities[0].properties[0]);

  /// see [Jwt.lastUpdatedAt]
  static final lastUpdatedAt =
      QueryIntegerProperty<Jwt>(_entities[0].properties[1]);

  /// see [Jwt.token]
  static final token = QueryStringProperty<Jwt>(_entities[0].properties[2]);

  /// see [Jwt.tokenType]
  static final tokenType = QueryStringProperty<Jwt>(_entities[0].properties[3]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// see [User.objectBoxId]
  static final objectBoxId =
      QueryIntegerProperty<User>(_entities[1].properties[0]);

  /// see [User.userName]
  static final userName = QueryStringProperty<User>(_entities[1].properties[1]);

  /// see [User.email]
  static final email = QueryStringProperty<User>(_entities[1].properties[2]);

  /// see [User.token]
  static final token =
      QueryRelationToOne<User, Jwt>(_entities[1].properties[3]);

  /// see [User.lastUpdatedAt]
  static final lastUpdatedAt =
      QueryIntegerProperty<User>(_entities[1].properties[4]);

  /// see [User.environment]
  static final environment =
      QueryStringProperty<User>(_entities[1].properties[5]);

  /// see [User.isDark]
  static final isDark = QueryBooleanProperty<User>(_entities[1].properties[6]);

  /// see [User.defaultLocale]
  static final defaultLocale =
      QueryStringProperty<User>(_entities[1].properties[7]);

  /// see [User.phoneNumber]
  static final phoneNumber =
      QueryStringProperty<User>(_entities[1].properties[8]);
}
